modLoader="javafml"
loaderVersion="[36,)"
license="https://github.com/Just-Chaldea/Forge-Client-Reset-Packet/blob/main/LICENSE"
issueTrackerURL="https://github.com/Just-Chaldea/Forge-Client-Reset-Packet/issues"

[[mods]]
modId="clientresetpacket"
version="0.0.6"
displayName="Client Reset Packet"
displayURL="https://github.com/Just-Chaldea/Forge-Client-Reset-Packet"
credits="https://github.com/Just-Chaldea/Forge-Client-Reset-Packet"
authors="https://github.com/Just-Chaldea/Forge-Client-Reset-Packet"
description='''
Adds a reset packet to Minecraft Forge to allow Modern Forge (1.13+) support on proxies.
'''
